theme: jekyll-theme-tactile

plugins:
	- jekyll-sitemap
	- jekyll-seo-tag

sass:
  sass_dir: assets/css

title: "Anna Oates"
tagline: ""
email: "annaireneo@gmail.com"
description: ""
>- # this means to ignore newlines until "baseurl:"
author: Anna Oates
baseurl: ""
url: "https://annaoates.github.io"
#google_analytics: UA-111111111-1
twitter:
  username: @annaoates
  card: summary #keep this to generate a twitter share card

logo: ""
